- next.config.js
- package-lock.json
See: https://github.com/WalletConnect/walletconnect-monorepo/issues/1908#issuecomment-1712429322
Fixes the noisy compiler errors:
```
Import trace for requested module:
./node_modules/pino/lib/tools.js
./node_modules/pino/pino.js
./node_modules/@walletconnect/logger/dist/cjs/index.js
./node_modules/@walletconnect/universal-provider/dist/index.es.js
./node_modules/@walletconnect/ethereum-provider/dist/index.es.js
./node_modules/@wagmi/connectors/dist/walletConnect.js
./node_modules/@wagmi/core/dist/connectors/walletConnect.js
./node_modules/wagmi/dist/connectors/walletConnect.js
./node_modules/@rainbow-me/rainbowkit/dist/index.js
./app/(routes)/providers.tsx
./app/(routes)/layout.tsx
⚠ ./node_modules/pino/lib/tools.js
Module not found: Can't resolve 'pino-pretty' in …
```
> Fix walletconnect import issue

- app/(routes)/proposals/[id]/page.tsx
- app/components/_shared/execution-code-view/execution-code-view.component.tsx
- app/components/_shared/execution-code-view/execution-code-view.module.scss
- app/components/_shared/index.tsx
- app/components/_shared/input/input.component.tsx
- app/components/_shared/see-all/see-all.component.tsx
- app/components/_shared/see-all/see-all.module.scss
- app/components/create-proposal/create-proposal-execution-step/create-proposal-execution-step.component.tsx
- app/components/create-proposal/create-proposal-preview-step/create-proposal-preview-step.component.tsx
- app/components/create-proposal/create-proposal-preview-step/create-proposal-preview-step.module.scss
- app/components/create-proposal/create-proposal-wallet-step/create-proposal-wallet-step.component.tsx
Add a new component to Execution code view and implement it in create new proposal page and Single proposal view
Add SeeAll component to expanding views and implement it to Execution code and Proposal description
n/a
PR build and lint successful
- Fixes #40 
n/a
n/a
> feat(governance-ui#40): add SeeAll component and Execution code view

- app/abis/TimelockController.ts
- app/components/contract-params/contract-params.component.tsx
- app/helpers/chains.ts
- app/helpers/wallet.helper.ts
- package.json
- pnpm-lock.yaml
This PR integrate the Mento SDK into the app, using the new governance functions to fetch and display chain specific governance parameters on the front end. 
_One thing to note is that we need an overlay for when a wrong chain is connected, but I'm not sure how this should look, so I'll chat with @olenovyk about this, I think it's good to begin review as it is_
Updated the address shortening function to accept intended length as a param
PR build and lint successful
- Fixes #21 
n/a
n/a
> feat: fetch & display governance params from mento sdk

- app/(routes)/page.tsx
Small fix on the info component to display the correct token supply and remove the ERC20 pill, according to the figma design.
Ran it locally
-  Fixes https://github.com/mento-protocol/governance-ui/issues/62
> fix: correct supply in info component

- app/(routes)/layout.tsx
- app/components/_shared/breadcrumbs/breadcrumbs.component.tsx
- app/components/_shared/breadcrumbs/breadcrumbs.module.scss
- app/helpers/routing.map.ts
Small fix on the breadcrumb component to:
1) fix the colors on the individual crumbs, as they were inverted from the figma design
2) add a short version of the proposal id when the user navigates to a specific proposal page
Ran it locally
-  Fixes https://github.com/mento-protocol/governance-ui/issues/66
> fix: bread crumb colors and missing proposal id

- .secretlintignore
- .secretlintrc.json
- package.json
- pnpm-lock.yaml
- src/config/valora.wallet.ts
This PR adds [secretlint](https://github.com/secretlint/secretlint) to our toolchain.
1. Check out this branch locally
2. Try it out with `npm run lint:secrets` => should be passing
3. Add a `SOME_SECRET=danger` to your `.env`
4. Run it again `npm run lint:secrets` => should be failing
> Add secretlint

- src/config/chains.ts
The hardcoded addresses are no longer relevant
> fix: remove hardcoded alfajores addresses

- src/app/(routes)/proposals/[id]/_components/execution-code.component.tsx
This PR updates the styling of the execution code headline to match the Proposal description one
- closes #125
> fix: heading styling

- src/components/create-proposal/create-proposal-wallet-step/create-proposal-wallet-step.component.tsx
This PR sets the max width for the locking component on the create proposal screen
- closes #134
> Fix(134): Locking component width 

- src/lib/contracts/useContractsInfo.ts
Fixes an issue where we expect the calldata to include params
> fix: update to allow decoding with params

- src/lib/contracts/governor/useGovernanceDetails.ts
This PR fixes the display of the voting period and the timelock period.
The existing code had an error with a check on the `rawParam.result !== undefined` since the input had no .result attribute, the code always returned null. 
Since the functions calling the formatParam function have their check for the param not being undefined I removed the check.
I also added a check for the period in days being 0. If that's the case the period is displayed in minutes to support our testnet setup. 
Fixes #149
> feat: fix time calculation for timelock and voting period

- src/app/(routes)/my-voting-power/page.tsx
- src/app/(routes)/proposals/[id]/page.tsx
- src/components/_icons/mento.icon.tsx
- src/components/_shared/loader/loader.component.tsx
- src/components/_shared/vote-loading-state/vote-loading-state.tsx
- src/components/locks-list/locks-list.component.tsx
- src/components/proposal-current-votes/proposal-current-votes.component.tsx
- src/components/vote-cast-vote/vote-confirmation.tsx
- src/lib/contracts/governor/useProposal.ts
- src/lib/contracts/locking/useLocksByAccount.ts
This PR resolves a data staleness issue when voting on a proposal. 
This PR additionally resolves an issue with the My Locks page, where in the event of an account not having any locks, a destructuring error would inject an empty `Partial<Lock>` which would cause  page render issues.
This is achieved by creating a block number watcher specifically when using the `useProposal` hook. This syncs the Apollo checks with the Tanstack queries.
- closes #155
> Fix(155): Voting update & My Locks page fix

- src/components/_shared/markdown-editor/markdown-editor.component.tsx
- src/components/vote-cast-vote/cast-vote.tsx
This PR fixes the lock on vote component
To test, create a proposal, then swap to a wallet that has no Mento or veMento
- closes #167
> Fix(167): Vote lock align 

- src/components/_shared/loader/loader.component.tsx
- src/components/_shared/modal/modal.component.tsx
- src/components/_shared/step-counter/step-counter.component.tsx
- src/components/_shared/tx-modal/tx-modal.component.tsx
- src/components/create-proposal/explainer-modal/execution-explainer.modal.tsx
This PR updates the modal to use the typical dark mode colors 
Basically switch to dark mode, go to create proposal, check the explainer modal on the code section in step 3
Then try create a proposal, but dont sign the transaction, check if the loading modal is correct, then decline signing the create proposal transaction, and see if the retry modal is correct as well
- closes #173
> Fix(173): Darkmode explainer

- src/lib/graphql/subgraph/generated/subgraph.tsx
- src/lib/graphql/subgraph/queries/getAllLocks.graphql
- src/lib/graphql/subgraph/queries/getDelegates.graphql
- src/lib/graphql/subgraph/queries/getLocks.graphql
- src/lib/graphql/subgraph/queries/getProposals.graphql
This increases the query returns to 1000
The actual fix will be adding another table to the graph for metrics on totals, this is required for predictable pagination later on anyway but for now this will return accurate data
> Fix: Minor fix while data patch to graph is created

- src/components/_icons/copy.icon.tsx
- src/components/_icons/dark-mode.icon.tsx
- src/components/_icons/light-mode.icon.tsx
- src/components/_shared/footer/footer.component.tsx
- src/components/_shared/learn-more/learn-more.component.tsx
Going through to fix some latent visual mobile issues
_An explanation of how the changes were tested or an explanation as to why they don't need to be._
- Fixes #166
> Fix(166): General mobile issues

- src/lib/helpers/ensureChainId.ts
The logic for ensuring correct data was blocking Alfajores access on Dev environments due to incorrect logic in the chain checking function
> Hotfix: Alfajores subgraph patch

- src/components/_shared/learn-more/learn-more.component.tsx
Minor fix to correct width of discord join button. 
- Closes #208 
Before:
After:
> fix: join discord button width

- .secretlintignore
- src/components/proposal-summary/proposal-summary.component.tsx
- src/components/proposals-list/proposals-list.component.tsx
Implementing our decision-by-poll on this little naming change: 
Also fine-tuned some spacings around the proposal summary component.
> Change "Voters" to "Registered Voters" in Proposal Summary section on landing page

- src/app/error.tsx
- src/app/global-error.tsx
- src/app/proposals/[id]/page.tsx
- src/lib/contracts/governor/useProposal.ts
- src/lib/contracts/useTokens.ts
This PR fixes an issue where the proposal page crashes randomly, often after some time on the page. This crashing behavior was caused by an error thrown within an external library. Three main things contributed to this. 
- The library we were using to query the graph (Apollo) threw an unhandled error in the proposal fetching hook
- We didn't have a global error page to catch these unhandled errors
- We were polling the graph too many times, which caused the graph to throttle us
I've added an error page to catch any unhandled errors like this & made changes to poll less & read from the cache more often. We should also look at our subgraph to see if we can increase the request limit
**For Reviewers**
You can replicate the error by visiting the [governance site](https://governance.mento.org) …
> Fix: Proposal page error handling

- .github/workflows/lint.yaml
cache v2 is deprecated and causing ci to fail. this pr upgrades cache action to v4
> chore: use cachev4
