mento-protocol/governance-ui

app/(routes)/proposals/[id]/page.tsx, app/components/_shared/progress-bar/progress-bar.component.tsx, app/components/_shared/progress-bar/progress-bar.module.scss, app/components/create-proposal/create-proposal-wallet-step/create-proposal-wallet-step.component.tsx, app/components/proposal-current-votes/proposal-current-votes.component.tsx, app/components/proposal-current-votes/proposal-current-votes.module.scss, next.config.js, package-lock.json
Add a new component to allow showing all vote values on single progress bar
Add voting details under the progress bar
n/a
PR build and lint successful
- Fixes #25 
n/a
n/a
=> feat(governance-ui#25): Add a component with overview of votes

.github/workflows/pull_request_template.md
**Description**
This adds a PR template to the repo.
=> chore: add pr template

app/(routes)/page.tsx
This is https://github.com/mento-protocol/governance-ui/pull/74 which I accidentally merged into main instead of develop
=> fix: correct supply in info component (#74)

app/(routes)/proposals/[id]/_components/execution-code.component.tsx, app/components/_shared/card/card.component.tsx, app/components/_shared/card/card.module.scss, app/styles/variables.module.scss
- fix bug with section rounded corners
design changes:
- change border-radius value according to Figma
Go to main page -> look at section borders
Go to proposal page ->  look at Execution code section
Go to Add proposal form  -> look at section borders
-  Fixes #60
=> Fix(60)/fix bug with rounded corners

src/components/_shared/connect-button/connect-button.component.tsx, src/components/_shared/mento-lock/mento-lock.component.tsx, src/components/create-proposal/create-proposal-wallet-step/create-proposal-wallet-step.component.tsx, src/components/vote-cast-vote/locked-balance.tsx, src/lib/contracts/useTokens.ts
@AnnaJ-P11  Picked up that the balances weren't pullling through, so this was a mistake on my part assuming balance pulled user context, but the approach is deprecated anyway so refactored to wagmi 2 recommendations
=> Fix: Balances not pulling through | Refactored from `useBalance` 

src/app/(routes)/page.tsx, src/components/contract-params/contract-params.component.tsx
This PR updates header font sizesto match designs 
- closes #118
=> fix: text sizes on mobile devices

src/components/_shared/vote-loading-state/vote-loading-state.tsx, src/components/proposal-current-votes/proposal-current-votes.component.tsx, src/components/vote-cast-vote/cast-vote.tsx, src/components/vote-inactive-proposal-status-message/inactive-proposal-status-message.tsx
This PR fixes card alignment in the voting (view proposal) page 
- closes #123
=> Fix:voting page alignment

src/app/(routes)/page.tsx
This PR adds the correct 'my voting power' link styling to the mobile version
- closes #119
=> fix: add correct voting page link on mobile

package.json, pnpm-lock.yaml, src/app/(routes)/layout.tsx, src/components/_shared/block-explorer-link/block-explorer-link.component.tsx, src/components/_shared/wallet-address-with-copy/wallet-address-with-copy.component.tsx, src/components/contract-params/contract-params.component.tsx, src/components/wallet-address/wallet-address.component.tsx, src/config/chains.ts, src/lib/contracts/governor/useGovernanceDetails.ts, src/lib/contracts/useContracts.ts
This PR updates header styling to match designs 
- closes #120
=> fix: gov contract address copy functionality

package.json, pnpm-lock.yaml
**Description**
Update to use the latest version of  the SDK.
=> feat: update sdk version

src/lib/contracts/useContracts.ts, src/lib/hooks/useEnsureChain.ts
This prevents crashing when the wallet is connected to a non Celo network
=> Fix: Crashing on other networks

src/app/(routes)/proposals/[id]/page.tsx, src/lib/graphql/celo-explorer/generated/celoGraph.tsx, src/lib/graphql/subgraph/fragments/proposalFields.graphql, src/lib/graphql/subgraph/generated/subgraph.tsx
This Pr adds a countdown showing the timelock period when a proposal is queued
=> feat: add timelock cooldown

src/components/_shared/input/input.component.tsx, src/components/_shared/textarea/textarea.component.tsx
Removes redundant focus on inputs
- closes #136
=> Fixed focus issue on input

src/components/_shared/footer/footer.component.tsx, src/components/proposals-list/proposals-list.component.tsx
This PR updates the proposal list to reflect the designs as well as makes a minor fix to the footer on mobile.
- closes #126
=> Fix(126): Mobile proposal list

src/app/(routes)/proposals/[id]/page.tsx, src/components/_shared/connect-button/connect-button.component.tsx, src/components/_shared/header/mobile-header.tsx, src/config/wagmi.config.ts, src/lib/contracts/useContracts.ts, src/lib/hooks/useEnsureChain.ts, src/middleware.ts
In order to prevent issues arrising from routing when sharing Alfajores proposals, for the time being, this PR will allow us to enforce access to just CELO while the issue is resolved
Unfortunately, due to requiring a Vercel envrionment variable, this will be simplely a code review, test the deployment to see if all Alfajore's related code still works when not in prod.
To Test locally however, add the following to your `env.local`
```env
NEXT_PUBLIC_VERCEL_ENV=production
```
=> Feat: Enforces that only CELO network is accessable on PROD

src/components/_shared/footer/footer.component.tsx, src/components/_shared/header/header-nav.tsx, src/components/_shared/mobile-accordion-menu.tsx, src/lib/constants/links.ts
removes the team link from all footers/headers
=> feat: update nav bars to not include team ref

src/app/privacy/page.tsx, src/components/_shared/footer/footer.component.tsx, src/lib/constants/links.ts, src/lib/helpers/routing.map.ts
Adds the Mento Foundation privacy notice to the site.
- None 
- Fixes #189
=> feat: add privacy

src/app/my-voting-power/page.tsx, src/components/locks-list/locks-list.component.tsx, src/components/withdraw/withdraw-button.tsx, src/lib/contracts/locking/useAvailableToWithdraw.ts, src/lib/contracts/locking/useWithdraw.ts
Updates My Voting Page to include a button to withdraw all unlocked Mento.
- None
- Checked mobile view and did [withdrawals](https://alfajores.celoscan.io/tx/0x64f3c7b71d94cad81a4531d46e20434048f59a49b0bb6c88184cbff4305c8f17) on Alfajores.
- Fixes #199
=> feat: add withdraw

src/app/my-voting-power/page.tsx
Disable locking until we sync on the required locking behavior
=> Temporarily disable locking

src/app/voting-power/page.tsx, src/components/_shared/mento-lock/components/locking-button.tsx, src/lib/hooks/useLockInfo.ts
It hides lock component for the users with active lock. 
- Fixes the bug with relocked filter
- Updates locking-button to use hasActiveLock
Yes
- Fixes #223
=> feat: block users from creating double lock

src/components/_shared/progress-bar/progress-bar.component.tsx, src/components/proposals-list/proposals-list.component.tsx
This Pr updates the mobile and desktop view of the proposal list to follow our figma design 
- Fixes #98
=> fix: mobile proposal list

src/app/proposals/[id]/_components/execution-code.component.tsx, src/app/proposals/[id]/_components/proposal-actions/disconnected-state.tsx, src/app/proposals/[id]/page.tsx, src/components/_shared/connect-button/connect-button.component.tsx, src/components/_shared/header/index.tsx, src/components/_shared/markdown-view/markdown-view.component.tsx, src/components/countdown/countdown.component.tsx, src/config/config.constants.ts, src/lib/contracts/governor/useProposal.ts, src/lib/contracts/useTokens.ts
Update the proposal page on mobile to match the Figma designs
N/A
Checked that both mobile & desktop views match designs
- Fixes #228
=> Feat: mobile proposal page

src/lib/helpers/ensureChain.tsx
_A few sentences describing the overall effects and goals of the pull request's commits.
What is the current behavior, and what is the updated/expected behavior with this PR?_
_Describe any minor or "drive-by" changes here._
_An explanation of how the changes were tested or an explanation as to why they don't need to be._
- Fixes #[issue number here]
=> fix: alfajores chain 3
